/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminNav: typeof import('./src/components/AdminNav.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FBIcon: typeof import('./src/components/icons/FBIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IGIcon: typeof import('./src/components/icons/IGIcon.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    ItemsNavPills: typeof import('./src/components/ItemsNavPills.vue')['default']
    LayoutFooter: typeof import('./src/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    LayoutNav: typeof import('./src/components/LayoutNav.vue')['default']
    LineIcon: typeof import('./src/components/icons/LineIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
